### ISSUE TITLE
Anlegen eines neuen Kunden scheitert dirket nach Installation

### ISSUE THREAD

**Issue by tyrant88** [greatif/kundenverwaltung#2]
![clipboard 1](https://user-images.githubusercontent.com/1277494/51679424-3b071a00-1fdf-11e9-926f-7e2396db81b1.jpg)

Error while executing statement "INSERT INTO `rex_kunden` SET "! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

**Comment by greatif** [comment]
Der Fehler müsste in der Version 0.77b behoben sein. Konntest Du nach dem Update Datensätze anlegen?

**Comment by tyrant88** [comment]
Kunden ja, Rechnungen nein. 
![clipboard 2](https://user-images.githubusercontent.com/1277494/53205528-da471d80-362e-11e9-97ba-8affe94df114.jpg)
![clipboard 1](https://user-images.githubusercontent.com/1277494/53205529-da471d80-362e-11e9-9e14-6ad468f1fe1a.jpg)

**Comment by tyrant88** [comment]
Kunden anlegen geht
